:_content-type: ASSEMBLY
[id="serverless-config-tls"]
= Configuring TLS authentication
include::../includes/common-attributes.adoc[]
:context: serverless-config-tls


You can use _Transport Layer Security_ (TLS) to encrypt Knative traffic and for authentication.

TLS is the only supported method of traffic encryption for Knative Kafka. Red Hat recommends using both SASL and TLS together for Knative broker for Apache Kafka resources.

[NOTE]
====
If you want to enable internal TLS with a {SMProductName} integration, you must enable {SMProductShortName} with mTLS instead of the internal encryption explained in the following procedure.

For {ocp-product-title} and {rosa-product-title}, see the documentation for link:https://access.redhat.com/documentation/en-us/red_hat_openshift_serverless/1.29/html-single/integrations/#serverless-ossm-enabling-serving-metrics_serverless-ossm-setup[Enabling Knative Serving metrics when using Service Mesh with mTLS].
====

include::../includes/serverless-enabling-tls-internal-traffic.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* link:https://access.redhat.com/documentation/en-us/red_hat_openshift_serverless/1.29/html-single/eventing/#serverless-kafka-broker-tls-default-config_kafka-broker[Configuring TLS authentication for the Knative broker for Apache Kafka]
* link:https://access.redhat.com/documentation/en-us/red_hat_openshift_serverless/1.29/html-single/eventing/#serverless-kafka-tls-channels_serverless-kafka-admin-security-channels[Configuring TLS authentication for channels for Apache Kafka]
* link:https://access.redhat.com/documentation/en-us/red_hat_openshift_serverless/1.29/html-single/integrations/#serverless-ossm-enabling-serving-metrics_serverless-ossm-setup[Enabling Knative Serving metrics when using Service Mesh with mTLS]
