:_content-type: ASSEMBLY
[id="installing-knative-eventing"]
= Installing Knative Eventing
include::includes/common-attributes.adoc[]
:context: installing-knative-eventing


To use event-driven architecture on your cluster, install Knative Eventing. You can create Knative components such as event sources, brokers, and channels and then use them to send events to applications or external systems.

After you install the {ServerlessOperatorName}, you can install Knative Eventing by using the default settings, or configure more advanced settings in the `KnativeEventing` custom resource (CR). For more information about configuration options for the `KnativeEventing` CR, see xref:serverless-configuration[Global configuration].

[IMPORTANT]
====
If you want to link:https://access.redhat.com/documentation/en-us/red_hat_openshift_serverless/1.29/html-single/observability/#serverless-tracing[use {DTProductName} with {ServerlessProductName}], you must install and configure {DTProductName} before you install Knative Eventing.
====

include::includes/serverless-install-eventing-web-console.adoc[leveloffset=+1]
include::includes/serverless-install-eventing-yaml.adoc[leveloffset=+1]

include::includes/serverless-install-kafka-odc.adoc[leveloffset=+1]

[id="next-steps_installing-knative-eventing"]
== Next steps

* If you want to use Knative services you can xref:installing-knative-serving[install Knative Serving].
