:_content-type: ASSEMBLY
include::includes/common-attributes.adoc[]
[id="install-serverless-operator"]
= Installing the {ServerlessOperatorName}
:context: install-serverless-operator


Installing the {ServerlessOperatorName} enables you to install and use Knative Serving, Knative Eventing, and the Knative broker for Apache Kafka on a {ocp-product-title} cluster. The {ServerlessOperatorName} manages Knative custom resource definitions (CRDs) for your cluster and enables you to configure them without directly modifying individual config maps for each component.

// universal install doc
include::includes/serverless-install-web-console.adoc[leveloffset=+1]

[IMPORTANT]
====
If you want to link:https://access.redhat.com/documentation/en-us/red_hat_openshift_serverless/1.29/html-single/observability/#serverless-tracing[use {DTProductName} with {ServerlessProductName}], you must install and configure {DTProductName} before you install Knative Serving or Knative Eventing.
====

include::includes/serverless-install-cli.adoc[leveloffset=+1]

[IMPORTANT]
====
If you want to link:https://access.redhat.com/documentation/en-us/red_hat_openshift_serverless/1.29/html-single/observability/#serverless-tracing[use {DTProductName} with {ServerlessProductName}], you must install and configure {DTProductName} before you install Knative Serving or Knative Eventing.
====


[id="serverless-configuration"]
== Global configuration

The {ServerlessOperatorName} manages the global configuration of a Knative installation, including propagating values from the `KnativeServing` and `KnativeEventing` custom resources to system link:https://kubernetes.io/docs/concepts/configuration/configmap/[config maps]. Any updates to config maps which are applied manually are overwritten by the Operator. However, modifying the Knative custom resources allows you to set values for these config maps.

Knative has multiple config maps that are named with the prefix `config-`. All Knative config maps are created in the same namespace as the custom resource that they apply to. For example, if the `KnativeServing` custom resource is created in the `knative-serving` namespace, all Knative Serving config maps are also created in this namespace.

The `spec.config` in the Knative custom resources have one `<name>` entry for each config map, named `config-<name>`, with a value which is be used for the config map `data`.

[id="additional-resources_knative-serving-CR-config"]
[role="_additional-resources"]
== Additional resources for {ocp-product-title}
* link:https://docs.openshift.com/container-platform/latest/operators/understanding/crds/crd-managing-resources-from-crds.html[Managing resources from custom resource definitions]
* link:https://docs.openshift.com/container-platform/latest/storage/understanding-persistent-storage.html#understanding-persistent-storage[Understanding persistent storage]
* link:https://docs.openshift.com/container-platform/latest/networking/configuring-a-custom-pki.html[Configuring a custom PKI]

[id="next-steps_install-serverless-operator"]
== Next steps

* After the {ServerlessOperatorName} is installed, you can xref:installing-knative-serving[install Knative Serving] or xref:installing-knative-eventing[install Knative Eventing].
